### PR TITLE
ImageData - First step towards central thread variable.

### PR DESCRIPTION
**Pull request by jomey**
This is my first hunch. Looking further at the threading logic and consolidate the structure for non- vs distributed execution could simplify a few more pieces. Work in progress.

### CODE REVIEW

**Comment by scotthavens** [comment]
The `@property` is probably cleaner way to do this. The thread variables are quite a mess at the moment but a lot of that won't be cleaned up until we clean up some of the distribute function calls. For example, `precip` requires a lot of thread variables even though not all are used. Although cleaning up `precip` is a whole other beast... which will probably happen once Ernesto precip rescaling is ready to be incorporated.

**Comment by jomey** [comment]
The failing tests are the same that are failing on the original `18_threading` branch. Should we just merge this and take care of those on the original?

**Comment by scotthavens** [comment]
So merge your branch into `18_threading`?

**Comment by jomey** [comment]
> So merge your branch into `18_threading`?

Yup, if you are OK with this approach. The target for this PR is set to that. Only need to allow merging with not passed checks somehow

**Pull request merged**
